name             'aar'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures aar'
long_description 'Installs/Configures aar'
version          '0.1.0'

depends 'ark'
depends 'mysql'
depends 'httpd'
depends 'python'
depends 'openssl'
depends 'database'
